Repository nextcloud/3rdparty, pull requests merged in 2019-01, with the labels that each got.

#191 Broker: add timezone to CANCEL messages
  patches.txt
  sabre/vobject/lib/ITip/Broker.php
Labels: 3. to review, enhancement

#186 Try to support 7.3 for DAV
  sabre/dav/lib/CalDAV/ICSExportPlugin.php
  sabre/dav/lib/DAV/CorePlugin.php
  sabre/vobject/lib/Component/VCard.php
  sabre/vobject/lib/FreeBusyGenerator.php
Labels: backport-request

#216 [stable13] pear/archive_tar 1.4.5
  composer.json
  composer.lock
  composer/ClassLoader.php
  composer/autoload_files.php
  composer/autoload_psr4.php
  composer/autoload_real.php
  composer/autoload_static.php
  composer/include_paths.php
  composer/installed.json
  pear/archive_tar/.gitignore
  pear/archive_tar/Archive/Tar.php
  pear/archive_tar/README.md
  pear/archive_tar/composer.json
  pear/archive_tar/package.xml
Labels: 2. developing

#225 Remove patch that was shipped with dbal 2.6.x
  patches.txt
Labels: 3. to review
