Repository nextcloud/3rdparty, pull requests merged in 2020-12, with the labels that each got.

#540 Replace abandoned log normalizer with our fork
  .gitignore
  composer.json
  composer.lock
  composer/ClassLoader.php
  composer/InstalledVersions.php
  composer/autoload_classmap.php
  composer/autoload_files.php
  composer/autoload_psr4.php
  composer/autoload_real.php
  composer/autoload_static.php
  composer/installed.json
  composer/installed.php
  composer/platform_check.php
  interfasys/lognormalizer/AUTHORS.md
  nextcloud/lognormalizer/COPYING
  nextcloud/lognormalizer/src/Normalizer.php
Labels: 3. to review, bug, enhancement

#543 [stable20] Replace abandoned log normalizer with our fork
  .gitignore
  composer.json
  composer.lock
  composer/autoload_classmap.php
  composer/autoload_psr4.php
  composer/autoload_static.php
  composer/installed.json
  interfasys/lognormalizer/AUTHORS.md
  nextcloud/lognormalizer/COPYING
  nextcloud/lognormalizer/src/Normalizer.php
Labels: 3. to review, bug

#546 Revert icewind/streams back to 0.7.1
  composer.json
  composer.lock
  composer/autoload_classmap.php
  composer/autoload_psr4.php
  composer/autoload_static.php
  composer/installed.json
  icewind/streams/.gitignore
  icewind/streams/src/CallbackWrapper.php
  icewind/streams/src/CountWrapper.php
  icewind/streams/src/Directory.php
  icewind/streams/src/DirectoryFilter.php
  icewind/streams/src/DirectoryWrapper.php
  icewind/streams/src/HashWrapper.php
  icewind/streams/src/IteratorDirectory.php
  icewind/streams/src/NullWrapper.php
  icewind/streams/src/Path.php
  icewind/streams/src/PathWrapper.php
  icewind/streams/src/ReadHashWrapper.php
  icewind/streams/src/RetryWrapper.php
  icewind/streams/src/SeekableWrapper.php
  icewind/streams/src/UrlCallBack.php
  icewind/streams/src/Wrapper.php
  icewind/streams/src/WrapperHandler.php
  icewind/streams/src/WriteHashWrapper.php
Labels: 4. to release

#521 Bump deepdiver/zipstreamer from 1.1.1 to 2.0.0
  composer.json
  composer.lock
  composer/InstalledVersions.php
  composer/autoload_classmap.php
  composer/autoload_static.php
  composer/installed.json
  composer/installed.php
  deepdiver/zipstreamer/.gitignore
  deepdiver/zipstreamer/composer.json
  deepdiver/zipstreamer/src/COMPR.php
  deepdiver/zipstreamer/src/Count64.php
  deepdiver/zipstreamer/src/Lib/Count64Base.php
  deepdiver/zipstreamer/src/Lib/Count64_32.php
  deepdiver/zipstreamer/src/Lib/Count64_64.php
  deepdiver/zipstreamer/src/ZipStreamer.php
  deepdiver/zipstreamer/src/lib/Count64.php
  deepdiver/zipstreamer/test/Count64Test.php
  deepdiver/zipstreamer/test/ZipComponents.php
  deepdiver/zipstreamer/test/ZipStreamerTest.php
  deepdiver/zipstreamer/test/bootstrap.php
  deepdiver/zipstreamer/test/integration/Dockerfile
  deepdiver/zipstreamer/test/integration/UnpackTest.php
  deepdiver/zipstreamer/test/phpunit.xml
Labels: 3. to review

#560 Bump icewind/streams from 0.7.1 to 0.7.2
  composer.json
  composer/InstalledVersions.php
  composer/autoload_classmap.php
  composer/autoload_static.php
  composer/installed.php
  icewind/streams/.gitignore
  icewind/streams/src/CallbackWrapper.php
  icewind/streams/src/CountWrapper.php
  icewind/streams/src/Directory.php
  icewind/streams/src/DirectoryFilter.php
  icewind/streams/src/DirectoryWrapper.php
  icewind/streams/src/HashWrapper.php
  icewind/streams/src/IteratorDirectory.php
  icewind/streams/src/NullWrapper.php
  icewind/streams/src/Path.php
  icewind/streams/src/PathWrapper.php
  icewind/streams/src/ReadHashWrapper.php
  icewind/streams/src/RetryWrapper.php
  icewind/streams/src/SeekableWrapper.php
  icewind/streams/src/UrlCallback.php
  icewind/streams/src/Wrapper.php
  icewind/streams/src/WrapperHandler.php
  icewind/streams/src/WriteHashWrapper.php
Labels: 3. to review, enhancement

#563 Require php7.3 or php8
  composer.json
  composer.lock
  composer/InstalledVersions.php
  composer/autoload_psr4.php
  composer/autoload_static.php
  composer/installed.json
  composer/installed.php
Labels: 3. to review

#573 Add TrimmedBufferOutput.php
  composer/InstalledVersions.php
  composer/autoload_classmap.php
  composer/autoload_static.php
  composer/installed.json
  composer/installed.php
  symfony/console/Output/TrimmedBufferOutput.php
Labels: 3. to review

#577 Invite the sabre family to the php8 party
  composer.lock
  composer/InstalledVersions.php
  composer/installed.json
  composer/installed.php
Labels: 3. to review, enhancement
