Repository nextcloud/3rdparty, pull requests merged in 2020-02, with the labels that each got.

#371 Add mikey179/vfsstream to gitignore
  .gitignore
Labels: 3. to review, technical debt

#400 Vendor #364 and #396 files
  .gitignore
  composer/autoload_classmap.php
  composer/autoload_static.php
  composer/installed.json
  guzzlehttp/guzzle/src/Client.php
  guzzlehttp/guzzle/src/ClientInterface.php
  guzzlehttp/guzzle/src/Cookie/CookieJar.php
  guzzlehttp/guzzle/src/Cookie/CookieJarInterface.php
  guzzlehttp/guzzle/src/Cookie/FileCookieJar.php
  guzzlehttp/guzzle/src/Cookie/SessionCookieJar.php
  guzzlehttp/guzzle/src/Cookie/SetCookie.php
  guzzlehttp/guzzle/src/Exception/ClientException.php
  guzzlehttp/guzzle/src/Exception/GuzzleException.php
  guzzlehttp/guzzle/src/Exception/RequestException.php
  guzzlehttp/guzzle/src/Exception/ServerException.php
  guzzlehttp/guzzle/src/Exception/TooManyRedirectsException.php
  guzzlehttp/guzzle/src/Exception/TransferException.php
  guzzlehttp/guzzle/src/Handler/CurlFactory.php
  guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php
  guzzlehttp/guzzle/src/Handler/MockHandler.php
  guzzlehttp/guzzle/src/Handler/StreamHandler.php
  guzzlehttp/guzzle/src/HandlerStack.php
  guzzlehttp/guzzle/src/MessageFormatter.php
  guzzlehttp/guzzle/src/Middleware.php
  guzzlehttp/guzzle/src/Pool.php
  guzzlehttp/guzzle/src/PrepareBodyMiddleware.php
  guzzlehttp/guzzle/src/RedirectMiddleware.php
  guzzlehttp/guzzle/src/RequestOptions.php
  guzzlehttp/guzzle/src/RetryMiddleware.php
  guzzlehttp/guzzle/src/TransferStats.php
  guzzlehttp/guzzle/src/functions.php
  guzzlehttp/psr7/CHANGELOG.md
  guzzlehttp/psr7/composer.json
  guzzlehttp/psr7/src/LimitStream.php
  guzzlehttp/psr7/src/MessageTrait.php
  guzzlehttp/psr7/src/Request.php
  guzzlehttp/psr7/src/Response.php
  guzzlehttp/psr7/src/ServerRequest.php
  guzzlehttp/psr7/src/Stream.php
  guzzlehttp/psr7/src/Uri.php
  guzzlehttp/psr7/src/functions.php
  ralouphie/getallheaders/composer.json
Labels: 3. to review, dependencies

#401 Add composer install check
  .github/workflows/composer.yml
  composer/autoload_classmap.php
  composer/autoload_static.php
Labels: 3. to review

#411 Fix composer binary permissions to allow updates
  .github/workflows/composer.yml
Labels: 3. to review
