Repository nextcloud/3rdparty, pull requests merged in 2023-09, with the labels that each got.

#1560 chore(deps): update sabre/http to 5.1.10 in stable27
  composer.lock
  composer/installed.json
  composer/installed.php
  sabre/http/lib/Auth/AbstractAuth.php
  sabre/http/lib/Auth/Basic.php
  sabre/http/lib/Auth/Bearer.php
  sabre/http/lib/Auth/Digest.php
  sabre/http/lib/Client.php
  sabre/http/lib/Message.php
  sabre/http/lib/MessageDecoratorTrait.php
  sabre/http/lib/MessageInterface.php
  sabre/http/lib/Request.php
  sabre/http/lib/RequestDecorator.php
  sabre/http/lib/RequestInterface.php
  sabre/http/lib/Response.php
  sabre/http/lib/ResponseDecorator.php
  sabre/http/lib/ResponseInterface.php
  sabre/http/lib/Sapi.php
  sabre/http/lib/Version.php
  sabre/http/lib/functions.php
Labels: 3. to review

#1579 Bump phpseclib/phpseclib to 2.0.45 in master
  composer.json
  composer.lock
  composer/installed.json
  composer/installed.php
  phpseclib/phpseclib/phpseclib/Crypt/Blowfish.php
  phpseclib/phpseclib/phpseclib/Crypt/DES.php
  phpseclib/phpseclib/phpseclib/Crypt/RC2.php
  phpseclib/phpseclib/phpseclib/Crypt/RC4.php
  phpseclib/phpseclib/phpseclib/File/ASN1.php
  phpseclib/phpseclib/phpseclib/File/X509.php
  phpseclib/phpseclib/phpseclib/Math/BigInteger.php
  phpseclib/phpseclib/phpseclib/Net/SFTP.php
  phpseclib/phpseclib/phpseclib/Net/SSH1.php
  phpseclib/phpseclib/phpseclib/Net/SSH2.php
Labels: 3. to review, dependencies, php

#1580 chore: remove opis/closure
  composer.json
  composer.lock
  composer/autoload_classmap.php
  composer/autoload_files.php
  composer/autoload_psr4.php
  composer/autoload_static.php
  composer/installed.json
  composer/installed.php
  opis/closure/LICENSE
  opis/closure/NOTICE
  opis/closure/autoload.php
  opis/closure/functions.php
  opis/closure/src/Analyzer.php
  opis/closure/src/ClosureContext.php
  opis/closure/src/ClosureScope.php
  opis/closure/src/ClosureStream.php
  opis/closure/src/ISecurityProvider.php
  opis/closure/src/ReflectionClosure.php
  opis/closure/src/SecurityException.php
  opis/closure/src/SecurityProvider.php
  opis/closure/src/SelfReference.php
  opis/closure/src/SerializableClosure.php
Labels: 3. to review, technical debt
