Repository nextcloud/3rdparty, pull requests merged in 2023-08, with the labels that each got.

#1483 chore: update symfony/mailer to 5.4.22
  composer.json
  composer.lock
  composer/installed.json
  composer/installed.php
  symfony/mailer/LICENSE
  symfony/mailer/Transport/Smtp/Stream/ProcessStream.php
Labels: 3. to review, dependencies

#1423 fix(deps): Upgrade symfony/event-dispatcher to supported version 5.4.26
  composer.json
  composer.lock
  composer/autoload_classmap.php
  composer/autoload_files.php
  composer/autoload_static.php
  composer/installed.json
  composer/installed.php
  symfony/deprecation-contracts/function.php
  symfony/event-dispatcher-contracts/Event.php
  symfony/event-dispatcher-contracts/EventDispatcherInterface.php
  symfony/event-dispatcher-contracts/LICENSE
  symfony/event-dispatcher/Attribute/AsEventListener.php
  symfony/event-dispatcher/Debug/TraceableEventDispatcher.php
  symfony/event-dispatcher/Debug/TraceableEventDispatcherInterface.php
  symfony/event-dispatcher/Debug/WrappedListener.php
  symfony/event-dispatcher/DependencyInjection/AddEventAliasesPass.php
  symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php
  symfony/event-dispatcher/Event.php
  symfony/event-dispatcher/EventDispatcher.php
  symfony/event-dispatcher/EventDispatcherInterface.php
  symfony/event-dispatcher/EventSubscriberInterface.php
  symfony/event-dispatcher/GenericEvent.php
  symfony/event-dispatcher/ImmutableEventDispatcher.php
  symfony/event-dispatcher/LICENSE
  symfony/event-dispatcher/LegacyEventDispatcherProxy.php
  symfony/event-dispatcher/LegacyEventProxy.php
  symfony/polyfill-php80/Resources/stubs/Attribute.php
  symfony/polyfill-php80/Resources/stubs/PhpToken.php
  symfony/polyfill-php80/Resources/stubs/Stringable.php
  symfony/polyfill-php80/Resources/stubs/UnhandledMatchError.php
  symfony/polyfill-php80/Resources/stubs/ValueError.php
Labels: bug, 3. to review

#1425 chore: update workflows from templates
  .github/workflows/lint-php.yml
Labels: 3. to review, dependencies, automated

#1352 Improvements at documentation
  README.md
Labels: enhancement
