Repository nextcloud/3rdparty, pull requests merged in 2024-01, with the labels that each got.

#1625 Add kornrunner/blurhash
  .gitignore
  composer.json
  composer.lock
  composer/autoload_classmap.php
  composer/autoload_psr4.php
  composer/autoload_static.php
  composer/installed.json
  composer/installed.php
  kornrunner/blurhash/LICENSE
  kornrunner/blurhash/src/AC.php
  kornrunner/blurhash/src/Base83.php
  kornrunner/blurhash/src/Blurhash.php
  kornrunner/blurhash/src/Color.php
  kornrunner/blurhash/src/DC.php
Labels: 2. developing

#1685 chore: update workflows from templates
  .github/workflows/lint-php.yml
Labels: 3. to review, dependencies, automated

#1684 chore: update workflows from templates
  .github/workflows/lint-php.yml
Labels: 3. to review, dependencies, automated

#1702 fix(deps): Remove deeper composer.lock files to fix security checking
  .gitignore
  cweagans/composer-patches/composer.lock
Labels: bug, 3. to review
